---

- name: Use provided configuration
  include_vars:
    file: "{{ test_configuration }}"
  when: test_configuration is defined

# This will prevent problems during checkout (__pycache__ folders will be owned by root)
- name: Fix permissions on kickstart tests repo
  file:
    path: "{{ kstest_git_repo }}"
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    recurse: yes

- name: Checkout kickstart tests repo
  become_user: "{{ kstest_remote_user }}"
  git:
    repo: "{{ kstest_git_repo }}"
    dest: "/home/{{ kstest_remote_user }}/{{ kstest.master.dir.git_repo }}"
    version: "{{ kstest_git_version }}"
    update: yes
    force: yes

- name: Install script for runners deployment check
  template:
    src: check_deployed_runners.sh.j2
    dest: "/home/{{ kstest_remote_user }}/{{ kstest.master.runners_check_script.dest }}"
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Get list of successfully deployed remote runners
  become_user: "{{ kstest_remote_user }}"
  command: "/home/{{ kstest_remote_user }}/{{ kstest.master.runners_check_script.dest }} \"{{ groups['kstest']|join(' ') }}\""
  register: remotes_check_result

- name: Set remotes to be used
  block:
    - set_fact:
        # The variable is used in the run_tests script template
        kstest_test_remotes: "{{ remotes_check_result.stdout }}"
        all_runners: "{{ groups['kstest']|join(' ') }}"
    - debug:
        msg: "WARNING: deployment check failed for some of the remote runners: ALL: '{{all_runners}}' DEPLOYED: '{{kstest_test_remotes}}'"
      when: kstest_test_remotes != all_runners
  when:
    remotes_check_result.rc == 0

- name: Install and configure script for remote run
  template:
    src: run_tests.sh.j2
    dest: /home/{{ kstest_remote_user }}/run_tests.sh
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Create directory for repos override fragment
  file:
    path: /home/{{ kstest_remote_user }}/{{ kstest.master.fragments_override_dir }}/{{ kstest.master.override_repos_file_path | dirname }}
    state: directory
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Create repos override fragment
  template:
    src: override_repos_default.ks.j2
    dest: /home/{{ kstest_remote_user }}/{{ kstest.master.fragments_override_dir }}/{{ kstest.master.override_repos_file_path }}
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755

- name: Create unified repo override fragment
  template:
    src: override_repos_unified.ks.j2
    dest: /home/{{ kstest_remote_user }}/{{ kstest.master.fragments_override_dir }}/{{ kstest.master.override_unified_repo_file_path }}
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755


- name: Install script for creating tests history summary
  copy:
    src: "{{ kstest.master.results_summary_script.src }}"
    dest: "/home/kstest/{{ kstest.master.results_summary_script.dest }}"
    owner: "{{ kstest_remote_user }}"
    group: "{{ kstest_remote_user }}"
    mode: 0755
  when: kstest.master.results_summary_script.src is defined
