---
### Schedule tests run in crontab

- name: Install crontab
  dnf:
    name: crontabs
    state: latest

- name: Enable and start crond service
  service:
    name: crond
    state: started
    enabled: yes

- name: Set up cron PATH
  cron:
    name: PATH
    user: "{{ kstest_remote_user }}"
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

- name: Configure scheduled test with cron
  cron:
    name: "Scheduled kickstart tests"
    hour: "{{ kstest_master_cron_hour }}"
    minute: "{{ kstest_master_cron_minute }}"
    user: "{{ kstest_remote_user }}"
    job: /home/{{ kstest_remote_user }}/run_tests.sh
    state: present
    disabled: "{{ kstest_master_cron_disabled }}"
