---
# run with --extra-vars "image_url=<boot iso URL>"
- hosts:
    kstest
  become: true
  become_user: root

  tasks:

  - name: Create directory for install images
    file:
      path: /home/kstest/install_images/
      state: directory
      owner: kstest
      group: kstest

  - name: Download new boot iso
    get_url:
      url: "{{ image_url }}"
      dest: /home/kstest/install_images/

