---
kstest_boot_iso_url: "https://download.fedoraproject.org/pub/fedora/linux/releases/29/Everything/x86_64/os/images/boot.iso"
kstest_updates_img: "http://rvykydal.fedorapeople.org/updates.user-patch.img"
kstest_url: "--url=https://download.fedoraproject.org/pub/fedora/linux/releases/29/Everything/x86_64/os"
kstest_tests_to_run: "user"
kstest_test_jobs: 1
