---

- hosts: runner-host
  become: yes
  gather_facts: no
  tasks:

    - name: Make sure python is installed for ansible
      raw: dnf -y install python3 python3-dnf
      register: python_installed
      changed_when: "'Nothing to do' in python_installed.stdout"

- hosts: runner-host
  become: yes
  vars_files:
    - vars.yml
  roles:
    - runner-host

