---

kstest:
  master:
    # ssh key to access remote hosts for running tests
    private_ssh_key:
    # set to "no" to prevent pulling the repository before the run
    git_pull: "yes"
    # schedule running test
    cron:
      disabled: true
      hour: 22
      minute: 00
    results_summary_script:
      src: files/scripts/kstests_history.py
      # relative path in home directory ("" to disable creating summary)
      dest: ""

    ### Locations (to be used by other playbooks)
    # relative path in home directory
    git_repo_dir: git/kickstart-tests
    # file names
    file:
      run: .run
      log: kstest.log
      result_report: result_report.txt
      test_parameters: test_parameters.txt
      isomd5sum: isomd5sum.txt
