---

- hosts: localhost
  become: false
  vars:
    master_key_name: "kstest-master"

  tasks:
  - name: Generate kstest user ssh key {{ kstest-master }}
    block:
      - tempfile:
          state: directory
          prefix: master-key-
        register: master_key_dir
      - debug:
          msg: "The keys will be generated in {{master_key_dir.path}}"
      - shell: ssh-keygen -b 2048 -t rsa -f {{ master_key_dir.path }}/kstest-master -q -N ""
        args:
          creates: "{{ master_key_dir.path }}/{{ master_key_name }}"
      - set_fact:
          master_private_ssh_key: "{{ master_key_dir.path }}/{{ master_key_name }}"
          master_public_ssh_key: "{{ master_key_dir.path }}/{{ master_key_name}}.pub"
    when:
      master_private_ssh_key is undefined and master_public_ssh_key is undefined

- hosts: kstest-master
  become: true
  become_user: root

  tasks:
  - include_vars: roles/kstest/vars/main.yml

  - name: Make sure kstest deployment tasks are done
    include_role:
      name: kstest

  - name: Install master ssh private key
    copy:
      src: "{{ hostvars['localhost']['master_private_ssh_key'] }}"
      dest: /home/{{ kstest_remote_user }}/.ssh/id_rsa
      owner: "{{ kstest_remote_user }}"
      group: "{{ kstest_remote_user }}"
      mode: 0600


  - name: Don't require remote kstest host authentication
    lineinfile:
      path: /home/{{ kstest_remote_user }}/.ssh/config
      create: yes
      owner: "{{ kstest_remote_user }}"
      group: "{{ kstest_remote_user }}"
      mode: 0600
      line: "{{ item }}"
    with_items:
      - "StrictHostKeyChecking no"
      - "UserKnownHostsFile=/dev/null"

- hosts:
    kstest
    kstest-master
  become: true
  become_user: root

  tasks:
  - include_vars: roles/kstest/vars/main.yml

  - name: Add authorized key for running remote tests
    authorized_key:
      user: "{{ kstest_remote_user }}"
      key: "{{ lookup('file', hostvars['localhost']['master_public_ssh_key']) }}"


- hosts: localhost
  become: false

  tasks:
  - name: Remove generated kstest user ssh key
    block:
      - file:
          path: "{{ master_key_dir.path }}/"
          state: absent
    when: master_key_dir is defined and master_key_dir.path is defined
