---
# Sync results from master kstest runner to local host into location
# provided by "local_dir" variable or created as temporary directory.

- hosts: localhost
  become: false

  tasks:
  - name: Create temporary local directory for results
    tempfile:
      state: directory
      prefix: kstest-results-
    register: kstest_results_dir
    when: local_dir is not defined

- hosts:
    kstest-master
  become: true
  become_user: root

  tasks:
  - include_vars: roles/kstest/vars/main.yml
  - include_vars: roles/kstest-master/vars/main/main.yml

  - name:
    set_fact:
      local_dir: "{{ hostvars['localhost']['kstest_results_dir']['path'] }}"
    when: local_dir is not defined

  - name: Make sure rsync required to fetch artifacts in installed
    dnf:
      name:
        - rsync

  - debug:
      msg: "Results will be synced into {{ local_dir }}"

  - name: Sync test results
    synchronize:
      mode: pull
      src: "/home/{{ kstest_remote_user }}/{{ kstest.master.dir.results }}/"
      dest: "{{ local_dir }}"
