---
# Stop running test in a way so results obtained so far can be gathered.
# Kills parallel process run by run_kickstart_tests.sh on master.

- hosts:
    kstest-master
  become: true
  become_user: root

  tasks:
  - name: Get the parallel process PID
    shell: pgrep parallel
    ignore_errors: yes
    register: pids_to_kill

  - block:
      - name: Parallel is not running -> finish
        debug:
          msg: "Unexpected number ( != 1) of 'parallel' process instances is running, I have no idea what to kill then."

      - meta: end_play
    when: pids_to_kill.stdout_lines | length != 1

  - name: Kill the process
    shell: kill {{ item }}
    with_items: "{{ pids_to_kill.stdout_lines }}"

  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
      timeout: 5
    with_items: "{{ pids_to_kill.stdout_lines }}"
    ignore_errors: yes
    register: killed_processes

  - name: Force kill the process
    shell: "kill -9 {{ item }}"
    with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
