---

kstest:
  master:
    # Script for generating summary from history of test results
    results_summary_script:
      src: files/scripts/kstests_history.py
      # relative path in home directory ("" to disable creating summary)
      dest: ""

    # Script for checking runners deployment
    runners_check_script:
      # relative path in home directory
      dest: "check_deployed_runners.sh"

    # Directory for fragment overrides
    fragments_override_dir: fragments_override
    # Fragment to be overriden with repos configured in test configuration
    override_repos_file_path: repos/default.ks
    # Fragment to be overriden with unified repo configured in test configuration
    override_unified_repo_file_path: repos/unified.ks

    ### Locations (to be used by other playbooks)
    file:
      run: .run
      log: kstest.log
      result_report: result_report.txt
      test_parameters: test_parameters.txt
      isomd5sum: isomd5sum.txt
      lorax_packages: lorax-packages.log
    # relative path in home directory
    dir:
      results: results
      git_repo: git/kickstart-tests

    ### Facts about installer iso image structure
    iso:
      # path to the image on the iso
      image_path: /images/install.img
      # rootfs path inside the image
      rootfs_path: /LiveOS/rootfs.img
      # path to file containing rpm versions used to build to the image
      lorax_packages_path: /root/lorax-packages.log
